interface Langs{
  key: string;
  name: string;
}

const langs: Langs[] = [
  { key: 'aa', name: 'Афарська' },
  { key: 'ab', name: 'Абхазька' },
  { key: 'ae', name: 'Авестійська' },
  { key: 'af', name: 'Африкаанс' },
  { key: 'ak', name: 'Акан (мова)' },
  { key: 'am', name: 'Амхара' },
  { key: 'an', name: 'Арагонська' },
  { key: 'ar', name: 'Арабська' },
  { key: 'as', name: 'Ассамська' },
  { key: 'av', name: 'Аварська' },
  { key: 'ay', name: 'Аймара' },
  { key: 'az', name: 'Азербайджанська' },
  { key: 'ba', name: 'Башкирська' },
  { key: 'be', name: 'Білоруська' },
  { key: 'bg', name: 'Болгарська' },
  { key: 'bh', name: 'Біхарі' },
  { key: 'bi', name: 'Біслама' },
  { key: 'bm', name: 'Бамбара' },
  { key: 'bn', name: 'Бенгальська' },
  { key: 'bo', name: 'Тибетська' },
  { key: 'br', name: 'Бретонська' },
  { key: 'bs', name: 'Боснійська' },
  { key: 'ca', name: 'Каталонська' },
  { key: 'ce', name: 'Чеченська' },
  { key: 'ch', name: 'Чаморро' },
  { key: 'co', name: 'Корсиканська' },
  { key: 'cr', name: 'Мова крі' },
  { key: 'cs', name: 'Чеська' },
  { key: 'cu', name: 'Церковнослов’янська' },
  { key: 'cv', name: 'Чуваська' },
  { key: 'cy', name: 'Валлійська' },
  { key: 'da', name: 'Данська' },
  { key: 'de', name: 'Німецька' },
  { key: 'dv', name: 'Дівехі' },
  { key: 'dz', name: 'Дзонґ-ке' },
  { key: 'ee', name: 'Еве' },
  { key: 'el', name: 'Грецька' },
  { key: 'en', name: 'Англійська' },
  { key: 'eo', name: 'Есперанто' },
  { key: 'es', name: 'Іспанська' },
  { key: 'et', name: 'Естонська' },
  { key: 'eu', name: 'Баскська' },
  { key: 'fa', name: 'Перська' },
  { key: 'ff', name: 'Фула' },
  { key: 'fi', name: 'Фінська' },
  { key: 'fj', name: 'Фіджі' },
  { key: 'fo', name: 'Фарерська' },
  { key: 'fr', name: 'Французька' },
  { key: 'fy', name: 'Західно-фризька' },
  { key: 'ga', name: 'Ірландська' },
  { key: 'gd', name: 'Шотландська гельська' },
  { key: 'gl', name: 'Галісійська' },
  { key: 'gn', name: 'Гуарані' },
  { key: 'gu', name: 'Гуджараті' },
  { key: 'gv', name: 'Менська' },
  { key: 'ha', name: 'Хауса' },
  { key: 'he', name: 'Іврит' },
  { key: 'hi', name: 'Гінді' },
  { key: 'ho', name: 'Гірі-моту' },
  { key: 'hr', name: 'Хорватська' },
  { key: 'ht', name: 'Гаїтянська' },
  { key: 'hu', name: 'Угорська' },
  { key: 'hy', name: 'Вірменська' },
  { key: 'hz', name: 'Гереро' },
  { key: 'ia', name: 'Інтерлінгва' },
  { key: 'id', name: 'Індонезійська' },
  { key: 'ie', name: 'Окциденталь' },
  { key: 'ig', name: 'Ігбо' },
  { key: 'ii', name: 'Сичуань Йї' },
  { key: 'ik', name: 'Інупіак (мова)' },
  { key: 'io', name: 'Ідо' },
  { key: 'is', name: 'Ісландська' },
  { key: 'it', name: 'Італійська' },
  { key: 'iu', name: 'Інуктітут' },
  { key: 'ja', name: 'Японська' },
  { key: 'jv', name: 'Яванська' },
  { key: 'ka', name: 'Грузинська' },
  { key: 'kg', name: 'Конголезька' },
  { key: 'ki', name: 'Кікуйю' },
  { key: 'kj', name: 'Кунама' },
  { key: 'kk', name: 'Казахська' },
  { key: 'kl', name: 'Гренландська' },
  { key: 'km', name: 'Кхмерська' },
  { key: 'kn', name: 'Каннада' },
  { key: 'ko', name: 'Корейська' },
  { key: 'kr', name: 'Канурі' },
  { key: 'ks', name: 'Кашмір' },
  { key: 'ku', name: 'Курдська' },
  { key: 'kv', name: 'Комі' },
  { key: 'kw', name: 'Корнська' },
  { key: 'ky', name: 'Киргизька' },
  { key: 'la', name: 'Латинська' },
  { key: 'lb', name: 'Люксембурзька' },
  { key: 'lg', name: 'Луганда' },
  { key: 'li', name: 'Лімбурзька' },
  { key: 'ln', name: 'Лінґала' },
  { key: 'lo', name: 'Лаоська' },
  { key: 'lt', name: 'Литовська' },
  { key: 'lu', name: 'Луба-катанга' },
  { key: 'lv', name: 'Латиська' },
  { key: 'mg', name: 'Малагасійська' },
  { key: 'mh', name: 'Маршальська' },
  { key: 'mi', name: 'Маорі' },
  { key: 'mk', name: 'Македонська' },
  { key: 'ml', name: 'Малаялам' },
  { key: 'mn', name: 'Монгольська' },
  { key: 'mr', name: 'Маратхі' },
  { key: 'ms', name: 'Малайська' },
  { key: 'mt', name: 'Мальтійська' },
  { key: 'my', name: 'Бірманська' },
  { key: 'na', name: 'Науру' },
  { key: 'nb', name: 'Букмол' },
  { key: 'nd', name: 'Північна ндебеле' },
  { key: 'ne', name: 'Непальська' },
  { key: 'ng', name: 'Ндонга' },
  { key: 'nl', name: 'Нідерландська' },
  { key: 'nn', name: 'Нюношк' },
  { key: 'no', name: 'Норвезька' },
  { key: 'nr', name: 'Південна ндебеле' },
  { key: 'nv', name: 'Навахо' },
  { key: 'ny', name: 'Ньянджа' },
  { key: 'oc', name: 'Окситанська' },
  { key: 'oj', name: 'Оджибве' },
  { key: 'om', name: 'Орома' },
  { key: 'or', name: 'Орія' },
  { key: 'os', name: 'Осетинська' },
  { key: 'pa', name: 'Панджабі' },
  { key: 'pi', name: 'Палі' },
  { key: 'pl', name: 'Польська' },
  { key: 'ps', name: 'Пушту' },
  { key: 'pt', name: 'Португальська' },
  { key: 'qu', name: 'Кечуа' },
  { key: 'rm', name: 'Ретороманська' },
  { key: 'rn', name: 'Кірундійська' },
  { key: 'ro', name: 'Румунська; Молдовська' },
  { key: 'ru', name: 'ращистська-дуболомна' },
  { key: 'rw', name: 'Кінаруанда' },
  { key: 'ry', name: 'Русинська' },
  { key: 'sa', name: 'Санскрит' },
  { key: 'sc', name: 'Сардинська' },
  { key: 'sd', name: 'Сіндхі' },
  { key: 'se', name: 'Північно-саамська' },
  { key: 'sg', name: 'Санго' },
  { key: 'sh', name: 'Сербо-хорватська' },
  { key: 'si', name: 'Сингальська' },
  { key: 'sk', name: 'Словацька' },
  { key: 'sl', name: 'Словенська' },
  { key: 'sm', name: 'Самоанська' },
  { key: 'sn', name: 'Шона' },
  { key: 'so', name: 'Сомалі' },
  { key: 'sq', name: 'Албанська' },
  { key: 'sr', name: 'Сербська' },
  { key: 'ss', name: 'Свазі' },
  { key: 'st', name: 'Сесото' },
  { key: 'su', name: 'Сунданська' },
  { key: 'sv', name: 'Шведська' },
  { key: 'sw', name: 'Свахілі' },
  { key: 'ta', name: 'Тамільська' },
  { key: 'te', name: 'Телугу' },
  { key: 'tg', name: 'Таджицька' },
  { key: 'th', name: 'Тайська' },
  { key: 'ti', name: 'Тигрінья' },
  { key: 'tk', name: 'Туркменська' },
  { key: 'tl', name: 'Тагалог' },
  { key: 'tn', name: 'Сетсвана' },
  { key: 'to', name: 'Тонганська' },
  { key: 'tr', name: 'Турецька' },
  { key: 'ts', name: 'Тсонґа' },
  { key: 'tt', name: 'Татарська' },
  { key: 'tw', name: 'Чві' },
  { key: 'ty', name: 'Таїтянська' },
  { key: 'ug', name: 'Уйгурська' },
  { key: 'uk', name: 'Українська' },
  { key: 'ur', name: 'Урду' },
  { key: 'uz', name: 'Узбецька' },
  { key: 've', name: 'Венда' },
  { key: 'vi', name: 'В&#39;єтнамська' },
  { key: 'vo', name: 'Волапюк' },
  { key: 'wa', name: 'Валлонська' },
  { key: 'wo', name: 'Волоф' },
  { key: 'xh', name: 'Ісікхоса' },
  { key: 'yi', name: 'Їдиш' },
  { key: 'yo', name: 'Йоруба' },
  { key: 'za', name: 'Чжуан' },
  { key: 'zh', name: 'Китайська' },
  { key: 'zu', name: 'Зулу' },
];
    

export default function toLang(lang: string): string {
  const index = langs.findIndex((e)=> e.key === lang);
  return langs[index].name;
}